### PR TITLE
2x2 grid

### LINKED ISSUE #1: 2x2 display for containers with more than one item type
As we discussed in the steam community channel, it would be nice to show the first four item types in a storage container if there is more than one. I've already started skimming through the code.

I'll see if there's a way to combine sprites into one sprite since that would require minimal changes to the cache object and such.

Worse comes to worst, I think having a "+" or "..." to indicate more item types would be helpful. But I have confidence I can get the 2x2 grid working. :)

### PR DESCRIPTION
**Pull request by nmay231**
Here's a working version for a 2x2 grid of items. Closes #1

The second commit has temporary code to see what icons would look like if they had a background to make items easier to see. It cycles every four seconds between background off, background on, and background on only if it contains items to compare the three options.

I just used one of the game assets, but we could probably add our own asset for a background. I think the glow should extend further out. My personal preference is to show a background only if it has items, but what are your thoughts?

### CODE REVIEW

**Comment by nmay231** [comment]
Closes #1

**Comment by Dr-Turtle** [comment]
The 2x2 icons look good, just needs a config. I don't find the background that you added to improve visibility, perhaps a dark background would work better given that inventory slots are dark. I agree that the background should only apply if icons are being displayed. Additionally, I would like the background to be configurable.

**Comment by nmay231** [comment]
> The 2x2 icons look good, just needs a config.

Sure thing. I originally thought it would be an enum of "single item", "2x2 grid", and "plus sign", but I guess a 2x2 grid and a plus for more items than presented could be separate booleans (a plus sign would mean more than 4 items when 2x2 grid is enabled). `{ "grid2x2": true, "displayPlusSignWhenExtraItems": true }`.

> I don't find the background that you added to improve visibility

It's part of the default game assets (`STEAM_FOLDER/Barotrauma/Content/UI/OuterGlow.png`), but that was just a temporary solution to see what it was like. I will copy it into this project or create a custom one so that any file rearranging they do doesn't break the mod.

> I agree that the background should only apply if icons are being displayed.

:+1:

> Additionally, I would like the background to be configurable.

Something like `{ "showBackgroundForContrast": true }`?

> perhaps a dark background would work better given that inventory slots are dark.

I initially thought that too, but it doesn't work as well. I think it's because the inventory slot is more medium gray than black, and it has gradient stripes to give even more contrast:

image

For comparison, here's a gray background, the current color choice, rgba(128, 128, 128, 128):

image

a black background rgba(0, 0, 0, 200) (you can barely see the black wire or paint):

image

and no background is better in some respects and worse in others (items start to blend in with the container itself):

image

**Comment by nmay231** [comment]
I lightened the background color to `rgba(128, 128, 128, 64)` (from alpha=128) and vendered in the image from Baro assets.

It's a little much to have the plus-sign and 2x2 grid, so I kept the plus-sign disabled by default.

Some examples:

image

image


image

**Comment by Dr-Turtle** [comment]
I'll test it later today, although before merging, I would like for the new config options to be configurable through commands. It's a lot more convenient than going to the config file

**Comment by nmay231** [comment]
Added a `config` command :+1:

**Comment by Dr-Turtle** [comment]
I have published these changes to the steam workshop, thanks for the contribution

**Pull request merged**
